### ISSUE TITLE
Add a visualization at commenting

### ISSUE THREAD

**Issue by soyapark-kaist** [soyapark-kaist/data-petition#13]
At previous Rally, the "교내 인터넷 데이터 첨부하기" button was not discoverable, users didn't use the feature as much as they want. Can you add an inviting interface for users to encourage them to add viz at their comment (@ dashboard.html)?

**Comment by todoaskit** [comment]
dashboard.html still does not work in my test environment.

## Error log
```
code: "app/no-app"
message: "Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app)."
name: "[DEFAULT]"
stack: "[DEFAULT]: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at error (https://www.gstatic.com/firebasejs/5.3.0/firebase.js:1:49471)
    at i (https://www.gstatic.com/firebasejs/5.3.0/firebase.js:1:49056)
    at Object.h [as database] (https://www.gstatic.com/firebasejs/5.3.0/firebase.js:1:48449)
    at showPetitionContent (http://localhost:8888/js/dashboard.js:40:30)
    at http://localhost:8888/js/dashboard.js:38:5"
```
```
code: "app/no-app"
message: "Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app)."
name: "[DEFAULT]"
stack: "[DEFAULT]: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at error (https://www.gstatic.com/firebasejs/5.3.0/firebase.js:1:49471)
    at Object.i [as app] (https://www.gstatic.com/firebasejs/5.3.0/firebase.js:1:49056)
    at e.constructor (http://localhost:8888/js/lib/mavo-firebase.min.js:1:756)
    at new e (http://localhost:8888/js/lib/mavo.js:1:2500)
    at Function.create (http://localhost:8888/js/lib/mavo.js:2909:20)
    at e.updateBackend (http://localhost:8888/js/lib/mavo.js:444:37)
    at backendTypes.forEach.role (http://localhost:8888/js/lib/mavo.js:97:37)
    at Array.forEach (<anonymous>)
    at e.constructor (http://localhost:8888/js/lib/mavo.js:97:16)
    at new e (http://localhost:8888/js/lib/mavo.js:1:2500)"
```
```
code: "app/no-app"
message: "Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app)."
name: "[DEFAULT]"
stack: "[DEFAULT]: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at error (https://www.gstatic.com/firebasejs/5.3.0/firebase.js:1:49471)
    at i (https://www.gstatic.com/firebasejs/5.3.0/firebase.js:1:49056)
    at Object.h [as database] (https://www.gstatic.com/firebasejs/5.3.0/firebase.js:1:48449)
    at initSignatureSummary (http://localhost:8888/js/dashboard.js:55:30)
    at http://localhost:8888/js/app.js:142:7
    at h.r2 (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ko.tZ0rnH_JYTs.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCP5rxMQrvMLsgNkRS8sXoWCXOm-Pg/cb=gapi.loaded_0:111:107)
    at xs (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ko.tZ0rnH_JYTs.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCP5rxMQrvMLsgNkRS8sXoWCXOm-Pg/cb=gapi.loaded_0:114:306)
    at Wq (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ko.tZ0rnH_JYTs.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCP5rxMQrvMLsgNkRS8sXoWCXOm-Pg/cb=gapi.loaded_0:114:186)
    at _.C.uea (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ko.tZ0rnH_JYTs.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCP5rxMQrvMLsgNkRS8sXoWCXOm-Pg/cb=gapi.loaded_0:114:52)
    at Ap (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.ko.tZ0rnH_JYTs.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCP5rxMQrvMLsgNkRS8sXoWCXOm-Pg/cb=gapi.loaded_0:107:284)"
```

## Test environment
- Chrome 
- macOS
- localhost, port 8888
- HEAD: 44a97d45809e2f1f72da07e41d5638d1b2c0e781

**Comment by soyapark-kaist** [comment]
Comment interface is ready.  https://github.com/soyapark-kaist/data-petition/blob/453e81696d29cfdf69a65f7f851f81f14311435b/js/storytelling.js#L31 this part has to be replaced. Reading boolean from an *inviting interface*, so that user don't miss that they can add a chart to comment
